remote_theme: chesterhow/tale
url: "https://woowacourse.github.io"
baseurl: "/review"

include:
  - _pages

logo: "/assets/favicon.ico"

permalink:    /:year-:month-:day/:title
paginate:     5

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
