remote_theme: chesterhow/tale
url: "https://woowacourse.github.io"
baseurl: "/javable"
title: "javable"

include:
  - _pages

logo: "/assets/favicon.ico"

permalink:    /:year-:month-:day/:title
paginate:     5

collections:
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  - scope:
      path: ''
      type: tags
    values:
      layout: tag

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-toc

whitelist:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-toc

safe: False